<?php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;

class FilmSeeder extends Seeder
{
    public function run(): void
    {
        $films = [
            [
                'title' => 'The Last Horizon',
                'description' => 'A breathtaking sci-fi epic about humanity\'s last stand against an alien invasion that threatens to consume the galaxy. Captain Aria leads a ragtag crew across uncharted space to find a weapon capable of saving Earth.',
                'genre' => ['Sci-Fi', 'Action'],
                'duration' => 148,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film1/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 15420,
            ],
            [
                'title' => 'Whispers in the Dark',
                'description' => 'A psychological thriller where a detective must unravel a series of mysterious disappearances in a small coastal town. Every clue leads deeper into a web of secrets that the townspeople would kill to protect.',
                'genre' => ['Thriller', 'Horror'],
                'duration' => 122,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film2/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 12300,
            ],
            [
                'title' => 'Love in Tokyo',
                'description' => 'Two strangers from different cultures find unexpected love during cherry blossom season in Tokyo. As their worlds collide, they must decide if love is worth the sacrifices they\'ll have to make.',
                'genre' => ['Romance', 'Drama'],
                'duration' => 115,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film3/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 8900,
            ],
            [
                'title' => 'Shadow Protocol',
                'description' => 'An elite covert agent is framed for a crime he didn\'t commit and must go rogue to clear his name. With every intelligence agency hunting him, he uncovers a conspiracy that goes all the way to the top.',
                'genre' => ['Action', 'Thriller'],
                'duration' => 135,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film4/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 18750,
            ],
            [
                'title' => 'The Haunting of Ravencroft',
                'description' => 'A family moves into a centuries-old mansion only to discover they are not alone. Dark forces lurk in every shadow, and the house itself seems to have a sinister agenda of its own.',
                'genre' => ['Horror', 'Drama'],
                'duration' => 108,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film5/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 7650,
            ],
            [
                'title' => 'Galactic Warriors',
                'description' => 'In a distant future, a band of unlikely heroes must unite to defeat the tyrannical empire that controls the galaxy. With incredible powers and unbreakable bonds, they fight for freedom.',
                'genre' => ['Sci-Fi', 'Action', 'Adventure'],
                'duration' => 156,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film6/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 22100,
            ],
            [
                'title' => 'Comedy Central Live',
                'description' => 'A hilarious comedy special featuring the world\'s funniest comedians in an unforgettable night of laughter. From stand-up to sketches, this show has something for everyone.',
                'genre' => ['Comedy'],
                'duration' => 95,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film7/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 5400,
            ],
            [
                'title' => 'The Dragon\'s Path',
                'description' => 'An ancient prophecy foretells the return of dragons to a war-torn kingdom. A young warrior must embark on a perilous journey to awaken the last dragon and restore peace to the realm.',
                'genre' => ['Adventure', 'Action'],
                'duration' => 142,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film8/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 11200,
            ],
            [
                'title' => 'Midnight Express',
                'description' => 'A gripping crime drama about a detective who works the night shift in a crime-ridden city. When a series of brutal murders shakes the city, she must confront her own demons to catch the killer.',
                'genre' => ['Drama', 'Thriller'],
                'duration' => 128,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film9/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 9800,
            ],
            [
                'title' => 'Eternal Sunshine',
                'description' => 'A deeply moving drama about a couple who discover they can erase painful memories. As they wrestle with the decision, they learn that even the most painful memories shape who we are.',
                'genre' => ['Drama', 'Romance'],
                'duration' => 118,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film10/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 6700,
            ],
            [
                'title' => 'Speed Demons',
                'description' => 'The fastest drivers in the world compete in an underground racing circuit where the stakes are life and death. One driver must risk everything to take down the criminal organization behind it all.',
                'genre' => ['Action', 'Thriller'],
                'duration' => 131,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film11/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 14300,
            ],
            [
                'title' => 'The Forgotten Island',
                'description' => 'A group of explorers discover a hidden island where time stands still. Ancient creatures roam freely, and the explorers must survive long enough to find a way back to civilization.',
                'genre' => ['Adventure', 'Sci-Fi'],
                'duration' => 139,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film12/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 8100,
            ],
            [
                'title' => 'Laugh Factory',
                'description' => 'A struggling comedian gets one shot at stardom when he enters a national comedy competition. With his unique brand of humor and heart, he discovers that laughter truly is the best medicine.',
                'genre' => ['Comedy', 'Drama'],
                'duration' => 102,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film13/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 4500,
            ],
            [
                'title' => 'Neon City',
                'description' => 'In a dystopian future where corporations rule, a hacker discovers a dark secret that could bring down the entire system. Hunted by corporate assassins, she must decide what she\'s willing to sacrifice.',
                'genre' => ['Sci-Fi', 'Action', 'Thriller'],
                'duration' => 144,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film14/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 19800,
            ],
            [
                'title' => 'Heart of the Ocean',
                'description' => 'A marine biologist makes a groundbreaking discovery deep beneath the ocean\'s surface. But when a corporation seeks to exploit her findings, she must fight to protect the wonders she\'s found.',
                'genre' => ['Drama', 'Adventure'],
                'duration' => 126,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film15/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 7200,
            ],
            [
                'title' => 'The Conspiracy',
                'description' => 'A journalist stumbles upon a conspiracy that involves the highest levels of government. As she digs deeper, she realizes that the truth could cost her everything, including her life.',
                'genre' => ['Thriller', 'Drama'],
                'duration' => 133,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film16/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 10500,
            ],
            [
                'title' => 'Summer Nights',
                'description' => 'Three best friends spend their last summer together before college, navigating love, heartbreak, and the bittersweet reality of growing up. A coming-of-age story that resonates with everyone.',
                'genre' => ['Romance', 'Comedy', 'Drama'],
                'duration' => 109,
                'release_year' => 2023,
                'thumbnail' => 'https://picsum.photos/seed/film17/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 6300,
            ],
            [
                'title' => 'Iron Fist',
                'description' => 'A retired boxer is pulled back into the ring when his daughter is kidnapped by a crime lord. With nothing left to lose, he must fight his way through an underground tournament to save her.',
                'genre' => ['Action', 'Drama'],
                'duration' => 119,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film18/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 13600,
            ],
            [
                'title' => 'Phantom Manor',
                'description' => 'A paranormal investigation team enters a notorious haunted mansion to document supernatural activity. What they find inside is far more terrifying than anything they could have imagined.',
                'genre' => ['Horror', 'Thriller'],
                'duration' => 97,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film19/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => false,
                'views_count' => 8900,
            ],
            [
                'title' => 'Beyond the Stars',
                'description' => 'Humanity\'s first interstellar mission encounters an anomaly that challenges everything we know about the universe. The crew must decide whether to push forward or turn back before it\'s too late.',
                'genre' => ['Sci-Fi', 'Drama'],
                'duration' => 152,
                'release_year' => 2024,
                'thumbnail' => 'https://picsum.photos/seed/film20/400/600',
                'video_url' => 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
                'is_featured' => true,
                'views_count' => 16800,
            ],
        ];

        foreach ($films as $film) {
            Film::create($film);
        }
    }
}
