[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", 
           "php82Extensions.mbstring", "php82Extensions.xml", 
           "php82Extensions.curl", "php82Extensions.zip",
           "php82Extensions.gd",        # untuk image processing
           "php82Packages.composer",
           "nginx",                      # TAMBAHKAN INI
           "gettext"]                    # untuk envsubst

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan view:clear",
    "chmod +x /app/start.sh"
]

[start]
cmd = "bash /app/start.sh"